require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - db/schema.rb
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'tmp/**/*'

Bundler/OrderedGems:
  Include:
    - 'Gemfile'

Style/FrozenStringLiteralComment:
  Enabled: false
