---
version: '3.8'

x-app: &app
  image: rails-app:latest
  build:
    context: .
    dockerfile: Dockerfile
    target: production
  env_file:
    - .env
  environment:
    RAILS_LOG_TO_STDOUT: enabled

services:
  web:
    <<: *app
    command: bash -c "rm -rf /usr/src/app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "${PORT:-3000}:3000"

#  worker:
#    <<: *app
#    command: bundle exec sidekiq -C config/sidekiq.yml
