name: Update Template Repo

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 5 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: "!contains(github.event.head_commit.message, '[nodoc]')"
    steps:
    - uses: actions/checkout@v2
      with:
        repository: "Ruby-Starter-Kits/Docker-Rails-Template"
        path: App
        persist-credentials: false
    - uses: actions/checkout@v2
      with:
        repository: 'Ruby-Starter-Kits/Docker-Rails-Generator'
        path: Docker-Rails-Generator
        persist-credentials: false
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler: none
    - uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/App/node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-
    - name: Build Environment
      run: |
        cd $GITHUB_WORKSPACE/App
        bundle config path $GITHUB_WORKSPACE/vendor/bundle
        gem install rails
    - name: Clear previous build
      run: |
        cd $GITHUB_WORKSPACE/App
        shopt -s extglob
        rm -rfv !(".git"|"."|".."|"node_modules")
    - name: Build latest version of rails
      run: |
        cd $GITHUB_WORKSPACE/App
        rails new . --database=postgresql --skip-spring
    - name: Remove default Rails files I often remove pretty fast.
      run: |
        cd $GITHUB_WORKSPACE/App
        rm $GITHUB_WORKSPACE/App/config/credentials.yml.enc
        rm $GITHUB_WORKSPACE/App/config/master.key

        rm $GITHUB_WORKSPACE/App/app/views/layouts/mailer.text.erb
    - name: Copy Docker Files
      run: |
        cd $GITHUB_WORKSPACE/App
        rsync -a $GITHUB_WORKSPACE/Docker-Rails-Generator/App-Template/ $GITHUB_WORKSPACE/App/
    - name: Install Libraries I Often Use
      run: |
        cd $GITHUB_WORKSPACE/App
        echo "Remove gems I'm not a fan of"
        bundle remove jbuilder
        bundle remove web-console

        echo "Updating .gitignore to ignore .env files"
        cat .gitignore.append >> .gitignore
        rm .gitignore.append

        echo "Adding gems I often add next"
        cat Gemfile.append >> Gemfile
        rm Gemfile.append
        bundle

        echo "Installing RSpec"
        rm -rf test
        rails generate rspec:install

        echo "Sorting the Gemfile"
        gem install happy_gemfile
        happy_gemfile all
        bundle
        bundle exec rubocop Gemfile -A

        echo "Running RuboCop over everything"
        bundle exec rubocop -A --auto-gen-config
    - name: Pull docker image
      run: |
        cd $GITHUB_WORKSPACE/App
        docker-compose pull
    - uses: satackey/action-docker-layer-caching@v0
    - name: Test we can build docker
      run: |
        cd $GITHUB_WORKSPACE/App
        docker-compose build
    - name: Commit any new files
      run: |
        cd $GITHUB_WORKSPACE/App
        DOCKER_RAILS_INSTALLER_VERSION="Installer 0.4.0"
        RAILS_VERSION=`rails -v`

        git config --local user.email "github-actions@example.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -am "$RAILS_VERSION | $DOCKER_RAILS_INSTALLER_VERSION" || echo "No changes to commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.LOCAL_GIT_TOKEN }}
        repository: 'Ruby-Starter-Kits/Docker-Rails-Template'
        directory: App
